### ISSUE TITLE
Organization for Satyr related projects

### ISSUE THREAD

**Issue by kszucs** [daskos/mentor#50]
Satyr's main purpuse was to create [dask.mesos](https://github.com/lensacom/dask.mesos) used by an unreleased workflow manager called `epos`. Thus there is 4 packages reletad to each other depending mainly on mesos. I think it'd be reasonable to create an organization which holds these projects (like dask does). 

The mid term effect would be higher popularity, more contributor, slightly higher maintenance cost. The long term effect could be e.g. another marathon/chronos meta scheduler. 

Any thoughts?

cc @lazerviking 
cc @Arttii

**Comment by Arttii** [comment]
Sounds good to me, would love to unify stuff like that.

 My initial rational for looking at satyr was also coming from stumbling upon dask.mesos and a need for a pythonic way to write custom scheduler, but with advanced stuff akin to Netflix [Fenzo/Titus](http://techblog.netflix.com/2015/08/fenzo-oss-scheduler-for-apache-mesos.html). It's a bit ambitious, but I think Python would be nicely suited to this.

There's still a ton of work to be done on the core driver as well and make it a quality package, but I am interested in participating.

We of course would have to define how to do, version control, contributions, testing and etc. And to be honest, I am not super experienced with properly contributing to an open source project like this. But if that's not a huge blocker for you I think this is a good idea

**Comment by Arttii** [comment]
Also, might be premature, but maybe I could roll a slack channel for easy communication at some point?
